# Supported funding model platforms
#   community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
#   github:           # Replace with GitHub username(s)
#   issuehunt:        # Replace with a single IssueHunt username
#   ko_fi:            # Replace with a single Ko-fi username
#   liberapay:        # Replace with a single Liberapay username
#   open_collective:  # Replace with a single Open Collective username
#   otechie:          # Replace with a single Otechie username
#   patreon:          # Replace with a single Patreon username
#   tidelift:         # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
#   lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
#   polar:            # Replace with a single Polar username
#   buy_me_a_coffee:  # Replace with a single Buy Me a Coffee username
#   thanks_dev:       # Replace with a single thanks.dev username
#   custom:           # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']

github: krayon
#ko_fi:  krayon